"""change_models

Revision ID: a6835c1af66b
Revises: 7d2fe4dcf112
Create Date: 2024-04-30 21:22:29.893141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6835c1af66b'
down_revision: Union[str, None] = '7d2fe4dcf112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award_criteria', sa.Column('award_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'award_criteria', 'awards', ['award_id'], ['id'])
    op.add_column('book_genres', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('book_genres', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('book_genres', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book_genres', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'book_genres', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'book_genres', 'genres', ['genre_id'], ['id'])
    op.add_column('book_memos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('book_memos', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book_memos', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'book_memos', 'users', ['user_id'], ['id'])
    op.add_column('book_tags', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('book_tags', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('book_tags', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'book_tags', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'book_tags', 'users', ['user_id'], ['id'])
    op.add_column('reading_sessions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('reading_sessions', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reading_sessions', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'reading_sessions', 'users', ['user_id'], ['id'])
    op.add_column('user_awards', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('user_awards', sa.Column('award_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_awards', 'awards', ['award_id'], ['id'])
    op.create_foreign_key(None, 'user_awards', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_awards', type_='foreignkey')
    op.drop_constraint(None, 'user_awards', type_='foreignkey')
    op.drop_column('user_awards', 'award_id')
    op.drop_column('user_awards', 'user_id')
    op.drop_constraint(None, 'reading_sessions', type_='foreignkey')
    op.drop_constraint(None, 'reading_sessions', type_='foreignkey')
    op.drop_column('reading_sessions', 'book_id')
    op.drop_column('reading_sessions', 'user_id')
    op.drop_constraint(None, 'book_tags', type_='foreignkey')
    op.drop_constraint(None, 'book_tags', type_='foreignkey')
    op.drop_constraint(None, 'book_tags', type_='foreignkey')
    op.drop_column('book_tags', 'tag_id')
    op.drop_column('book_tags', 'book_id')
    op.drop_column('book_tags', 'user_id')
    op.drop_constraint(None, 'book_memos', type_='foreignkey')
    op.drop_constraint(None, 'book_memos', type_='foreignkey')
    op.drop_column('book_memos', 'book_id')
    op.drop_column('book_memos', 'user_id')
    op.drop_constraint(None, 'book_genres', type_='foreignkey')
    op.drop_constraint(None, 'book_genres', type_='foreignkey')
    op.drop_constraint(None, 'book_genres', type_='foreignkey')
    op.drop_column('book_genres', 'genre_id')
    op.drop_column('book_genres', 'book_id')
    op.drop_column('book_genres', 'user_id')
    op.drop_constraint(None, 'award_criteria', type_='foreignkey')
    op.drop_column('award_criteria', 'award_id')
    # ### end Alembic commands ###
